# Generated by Django 5.1.7 on 2025-06-16 19:16

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('FRUIT', 'Fruits'), ('VEG', 'Vegetables'), ('DAIRY', 'Dairy'), ('MEAT', 'Meat'), ('GRAIN', 'Grains'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('expiry_date', models.DateField(default=inventory.models.default_expiry_date)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
