# Generated by Django 5.1.7 on 2025-04-02 17:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('FRUIT', 'Fruits'), ('VEG', 'Vegetables'), ('DAIRY', 'Dairy'), ('MEAT', 'Meat'), ('GRAIN', 'Grains'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('expiry_date', models.DateField(default=datetime.datetime(2025, 4, 9, 17, 55, 22, 869726, tzinfo=datetime.timezone.utc))),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
