# Generated by Django 5.1.7 on 2025-04-02 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 9, 19, 37, 51, 566149, tzinfo=datetime.timezone.utc)),
        ),
    ]
