# Generated by Django 5.1.7 on 2025-04-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe_id',
            field=models.CharField(max_length=100),
        ),
    ]
